### ISSUE TITLE
Shelter seems to have problems recovering after a power outage

### ISSUE THREAD

**Issue by jaycedowell** [lwa-project/shelter#8]
The detection of the outage seems ok and it knows that devices become unreachable.  However, once the power is back on and the devices are back up the error condition does not clear.  The only way to get it to clear is by restarting the software.

**Comment by jaycedowell** [comment]
Should be fixed as of https://github.com/lwa-project/shelter/commit/e96b39de0e1a5b30c028d22aa8cfca218f40e410.

**Comment by jaycedowell** [comment]
This is still a problem for LWA-NA.

**Comment by jaycedowell** [comment]
Ah:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
   File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
   File "/lwa/software/shlThreads.py", line 587, in monitorThread
     self.SHLCallbackInstance.processUnreachable('%s-%s' % (type(self).__name__, str(self.id)))
   File "/lwa/software/shlFunctions.py", line 1207, in processUnreachable
    self.currentState['unreachableDevices'][unreachableDevice] = tUse
```

**Comment by jaycedowell** [comment]
It'll work - for real this time.
